RedisDemoUI/Models/ApplicationDbContext.cs
using System;
using System.Collections.Generic;
using System.Net;
using StackExchange.Redis;


namespace RedisDemoUI.Models
{
    public class ApplicationDbContext
    {
        private static string RedisServer => "localhost:6379";
        private static readonly ConnectionMultiplexer Connection = ConnectionMultiplexer.Connect(RedisServer);
        private static readonly EndPoint[] EndPoints = Connection.GetEndPoints();
        private static readonly IServer Server = Connection.GetServer(EndPoints[0]);
        public IDatabase Database = Connection.GetDatabase();
        public IEnumerable<RedisKey> Keys = Server.Keys();
    }
}

RedisDemoUI/Models/ErrorViewModel.cs
using System;

namespace RedisDemoUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RedisDemoUI/Models/NextBusinessCall.cs
namespace RedisDemoUI.Models
{
    public class NextBusinessCall
    {
        public string Name { get; set; }
        public string Company { get; set; }
        public string Phone { get; set; }
        public string Time { get; set; }
    }
}

RedisDemoUI/Models/Task.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RedisDemoUI.Models
{
    public class Task
    {
        [Required]
        public string Name { get; set; }
       
    }
}

RedisDemoUI/Models/TaskViewModel.cs
using System.Collections.Generic;
using StackExchange.Redis;

namespace RedisDemoUI.Models
{
    public static class CustomExtensions
    {
        public static string ToUpperFirstLetter(this string stringValue)
        {
            var stringValueArray = stringValue.ToCharArray(0, stringValue.Length);
            var UpperFirstLetter = stringValueArray[0].ToString().ToUpper();
            return stringValue.Replace(stringValueArray[0].ToString(), UpperFirstLetter); ;

        }
    }
    public class TaskViewModel
    {
        public TaskViewModel(HashEntry[] call)
        {
            Call = call;
            Tasks = new List<Task>();
            NextBusinessCall = new List<string>();
            PopulateNextBusinesCall();
        }
        public List<Task> Tasks { get; set; }
        private HashEntry[] Call { get; set; }

        public string CallHaskKeyValue => "call";

        public List<string> NextBusinessCall { get; private set; }

        private void PopulateNextBusinesCall()
        {
            foreach (var entry in Call)
            {
                string call = $"{entry.Name.ToString().ToUpperFirstLetter()}: {entry.Value}";
                NextBusinessCall.Add(call);
            }
        }

        
    }
}

RedisDemoUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RedisDemoUI.Models;

namespace RedisDemoUI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RedisDemoUI/Controllers/TasksController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RedisDemoUI.Models;
using StackExchange.Redis;
using Task = RedisDemoUI.Models.Task;

namespace RedisDemoUI.Controllers
{
    public class TasksController : Controller
    {
        private readonly ApplicationDbContext _db;
        private const string Tasks = "tasks";
        private const string NextBusinessCall = "call";

        public TasksController()
        {
            _db = new ApplicationDbContext();
        }
        public IActionResult Index()
        {
           
            var values = _db.Database.ListRange(Tasks).ToArray();
            var call = _db.Database.HashGetAll(NextBusinessCall);
            var taskViewModel = new TaskViewModel(call);
            foreach (var value in values)
            {
                var task = new Task {Name = value};
                taskViewModel.Tasks.Add(task);

            }

            return View(taskViewModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Task task)
        {
            if (ModelState.IsValid)
            {
                await _db.Database.ListRightPushAsync(Tasks, task.Name);
                return RedirectToAction(nameof(Index));
            }

            return View(task);
        }

        public async Task<IActionResult> Details(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                return NotFound();
            }

            var results = await _db.Database.ListRangeAsync(Tasks);

            if (results.All(i => i != name))
            {
                return NotFound();
            }

            var task = new Task()
            {
                Name = results.Single(i => i == name)
            };
             
            return View(task);
        }
        public async Task<IActionResult> Edit(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                return NotFound();
            }

            var results = await _db.Database.ListRangeAsync(Tasks);

            if (results.All(i => i != name))
            {
                return NotFound();
            }

            var task = new Task()
            {
                Name = results.Single(i => i == name)
            };
             
            return View(task);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string name, Task task)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var taskItem = await _db.Database.ListRangeAsync(Tasks, 1);
                task.Name = taskItem.First();

                return RedirectToAction(nameof(Index));
            }

            return View(task);
        }
        public async Task<IActionResult> Delete(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                return NotFound();
            }

            var results = await _db.Database.ListRangeAsync(Tasks);

            if (results.All(i => i != name))
            {
                return NotFound();
            }

            var task = new Task()
            {
                Name = results.Single(i => i == name)
            };
             
            return View(task);
        }

        public IActionResult EditCall()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCall(string name, NextBusinessCall nextCall)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                return NotFound();
            }

            var call = new[]
            {
                new HashEntry("name", $"{nextCall.Name}"),
                new HashEntry("company", $"{nextCall.Company}"),
                new HashEntry("phone", $"{nextCall.Phone}"),
                new HashEntry("time", $"{nextCall.Time}")
            };
            await _db.Database.HashSetAsync("call", call);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveTask(string name)
        {
            await _db.Database.ListRemoveAsync(Tasks, name);
            return RedirectToAction(nameof(Index));
        }
    }
}

RedisDemoUI/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

RedisDemoUI/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RedisDemoUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

RedisDemoUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RedisTask With C#</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Tasks" asp-action="Index" class="navbar-brand">RedisTask With C#</a>
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Tasks" asp-action="Index">RedisTask With C#</a></li>
                </ul>
            </div>*@
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - RedisTask With C#</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

RedisDemoUI/Views/Tasks/Create.cshtml
@model RedisDemoUI.Models.Task
@{
    ViewData["Title"] = "Create";
}

<br />
<h2>Add New Task</h2>
<hr />

<form asp-action="Create">
    <div class="row form-border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Name" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <br/>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-sm btn-primary"/>
            <input type="submit" asp-action="Index" value="Back to List" class="btn btn-sm btn-success"/>
        </div>
    </div>
</form>

RedisDemoUI/Views/Tasks/Delete.cshtml
@model RedisDemoUI.Models.Task
@{
    ViewData["Title"] = "Delete";
}

<br />
<h2>Delete Task</h2>
<hr />

<form asp-action="Delete">
    <div class="row form-border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Name" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <br/>
        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-sm btn-danger"/>
            <input type="submit" asp-action="Index" value="Back to List" class="btn btn-sm btn-success"/>
        </div>
    </div>
</form>

RedisDemoUI/Views/Tasks/Details.cshtml
@model RedisDemoUI.Models.Task
@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>
<hr/>

<div class="row form-border">
    <div class="form-group">
        <div class="row">
            <div class="col-sm-1">
                <label asp-for="Name"></label>
            </div>
            <div class="col-sm-4">
                <input asp-for="Name" disabled class="form-control"/>
            </div>
        </div>
    </div>
    <br/>
    <div class="form-group">
        <a asp-action="Edit" asp-route-name="@Model.Name" class="btn btn-sm btn-primary">Edit</a>
        <a asp-action="Index" class="btn btn-sm btn-success">Back To Tasks</a>
    </div>
</div>

RedisDemoUI/Views/Tasks/Edit.cshtml
@model RedisDemoUI.Models.Task
@{
    ViewData["Title"] = "Edit";
}

<br />
<h2>Edit Task</h2>
<hr />

<form asp-action="Edit">
    <div class="row form-border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Name" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <br/>
        <div class="form-group">
            <input type="submit" value="Update" class="btn btn-sm btn-primary"/>
            <input type="submit" asp-action="Index" value="Back to List" class="btn btn-sm btn-success"/>
        </div>
    </div>
</form>

RedisDemoUI/Views/Tasks/EditCall.cshtml
@model RedisDemoUI.Models.NextBusinessCall
@{
    ViewData["Title"] = "EditCall";
}

<h2>EditCall</h2>
<hr />


<form asp-action="EditCall">
    <div class="row form-border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Name" class="form-control" />
                </div>
            </div>         
            <hr/>
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Company"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Company" class="form-control" />
                </div>
            </div>   
            
            <hr/>
            
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Phone"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Phone" class="form-control" />
                </div>
            </div>        
            
            <hr/>
            
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Time"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Time" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Update" class="btn btn-sm btn-primary" />
            <input type="submit" asp-action="Index" value="Back to List" class="btn btn-sm btn-success" />
        </div>
    </div>
</form>

RedisDemoUI/Views/Tasks/Index.cshtml
@model TaskViewModel
@{
    ViewData["Title"] = "RedisTasks";
}

<br/>
<h3>Task List</h3>
<hr/>

<p>
    <a asp-action="Create" class="btn btn-sm btn-primary">Add Task</a>
</p>
<br/>

<div class="form-border">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Tasks")
            </th>
            <th></th>
        </tr>
        @foreach (var task in Model.Tasks)
        {
            <tr>
                <td>
                    @Html.DisplayFor(m => task.Name)
                </td>
            </tr>
            <td>
                <a asp-action="Edit" asp-route-name="@task.Name" class="btn btn-sm btn-success">Edit</a>
                <a asp-action="Details" asp-route-name="@task.Name" class="btn btn-sm btn-primary">Details</a>
                <a asp-action="Delete" asp-route-name="@task.Name" class="btn btn-sm btn-danger">Delete</a>
            </td>
        }
    </table>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Next Business Call")
            </th>
            <th></th>
        </tr>
        @foreach (var call in Model.NextBusinessCall)
        {
            <tr>
                <td>
                    @Html.DisplayFor(n => call)
                </td>
            </tr>
        }
        <td>
            <a asp-action="EditCall" asp-route-name="@Model.CallHaskKeyValue" class="btn btn-sm btn-success">Edit</a>
        </td>
    </table>
</div>